export const ADD_DATA = 'ADD_DATA';
export const ADD_NEW_DATA = 'ADD_NEW_DATA';
export const ADD_BACKEND_DATA = 'ADD_BACKEND_DATA';
export const ADD_BACKEND_DATA_SUCCESS = 'ADD_BACKEND_DATA_SUCCESS';
export const ADD_BACKEND_DATA_FAILURE = 'ADD_BACKEND_DATA_FAILURE';
